name: PyFunceble CI Porn-Records
on:
  push:
    branches:
      - 'master'
      - 'data-testing'
  pull_request:
    branches:
      - 'master'
  schedule:
    - cron: '58 */4 * * *'

env:
  GIT_NAME: '${{ secrets.GIT_NAME }}'
  GIT_EMAIL: '${{ secrets.GIT_EMAIL }}'
  GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
  BUILD_NUMBER: '${{ github.run_number }}'
  PYFUNCEBLE_AUTO_CONFIGURATION: 'YES'
  PYFUNCEBLE_DEBUG: True
  PYFUNCEBLE_DEBUG_LVL: critical
  #PYFUNCEBLE_DEBUG_ON_SCREEN: true
  # PYFUNCEBLE_CONFIG_DIR: '${{ github.workspace }}/.pyfunceble'
  # PYFUNCEBLE_OUTPUT_LOCATION: '${{ github.workspace }}/active_domains/'
  PYFUNCEBLE_DB_HOST: '${{ secrets.MYPDNS_DB_HOST }}'
  PYFUNCEBLE_DB_NAME: '${{ secrets.MYPDNS_DB_NAME }}'
  PYFUNCEBLE_DB_PORT: '${{ secrets.MYPDNS_DB_PORT }}'
  PYFUNCEBLE_DB_USERNAME: '${{ secrets.MYPDNS_DB_USER }}'
  PYFUNCEBLE_DB_PASSWORD: '${{ secrets.MYPDNS_DB_PASS }}'
  PYFUNCEBLE_DB_CHARSET: '${{ secrets.MYPDNS_DB_CHAR }}'

jobs:
  test_and_push:
    name: Run PyFunceble against the files and push result to repository
    runs-on: '${{ matrix.os }}'

    strategy:
      fail-fast: false
      matrix:
        python_version:
          - '3.9.5'
        os:
          - ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        name: Clone repository
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}

      # - name: Install conda AS WSL sucks
      #   run: |
      #     bash "${{ github.workspace }}/scripts/conda_install.sh"

      # - name: Setup conda
      #   uses: s-weigand/setup-conda@v1.0.5
      #   with:
      #     python-version: 3.9.5
      #     activate-conda: true
      #     update-conda: true

      # - name: Conda environment creation
      #   run: |
      #     conda create -q -n pyfunceble4
      #     source activate pyfunceble4

      - name: Python version
        run: python --version

      - name: Conda version
        run: conda --version

      - name: Setup PyFunceble
        run: |
          pip install --no-cache-dir --pre PyFunceble-dev>=4.0.0b56

      - name: PyFunceble version
        run: |
          PyFunceble --version

      - name: Install UHBW
        run: |
          pip install --no-cache-dir ultimate-hosts-blacklist-whitelist-dev

      - name: UHBW version
        run: |
          uhb_whitelist --version

      # - name: Run Whitelist
      #   run: |
      #     bash "${{ github.workspace }}/scripts/PrepareData.sh"

      - name: Availability test of porn records
        run: |
          echo "$(date +'%s')" > "${{ github.workspace }}/.trigger"
          bash "${{ github.workspace }}/scripts/DataTesting.sh"
