name: PyFunceble CI tests
on:
  push:
      branches:
      - "master"
  pull_request:
      branches:
      - "master"
  schedule:
      - cron: "0 * * * *"

env:
  PYFUNCEBLE_AUTO_CONFIGURATION: "YES"
  GIT_NAME: "${{ secrets.GIT_NAME }}"
  GIT_EMAIL: "${{ secrets.GIT_EMAIL }}"
  PYFUNCEBLE_CONFIG_DIR: "${{ github.workspace }}/.pyfunceble"
  PYFUNCEBLE_OUTPUT_LOCATION: "${{ github.workspace }}/active_domains/"
  GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  BUILD_NUMBER: "${{ github.run_number }}"

jobs:
  test_and_push:
    name: Run PyFunceble against the files and push result to repository
    runs-on: "${{ matrix.os }}"

    strategy:
      fail-fast: false
      matrix:
          python_version:
            - "3.9.1"
          os:
            - ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        name: Clone repository
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install PyFunceble
        run: |
          pip install --no-cache-dir --pre PyFunceble-dev
          pip install --no-cache-dir ultimate-hosts-blacklist-whitelist-dev

      - name: Get PyFunceble version
        run: |
          PyFunceble --version

      - name: Install UHBW
        run: |
          pip install --no-cache-dir ultimate-hosts-blacklist-whitelist-dev

      - name: Get UHBW version
        run: |
          uhb_whitelist --version

      - name: Run Whitelist
        run: |
          bash "${{ github.workspace }}/travis/PrepareData.sh"

      - name: Run Data testing
        run: |
          bash "${{ github.workspace }}/travis/DataTesting.sh"

      - name: Create local change
        run: |
          date +%s > "${{ github.workspace }}/.trigger"

      - name: Commit changes
        run: |
          git config --local user.email "$GIT_EMAIL"
          git config --local user.name "$GIT_NAME"
          git commit -m "Launch test" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force: true
